### ISSUE TITLE
Magerun command to analyse interceptors

### ISSUE THREAD

**Issue by jissereitsma** [magento-hackathon/developer-paradise-2016#12]
With interceptors / plugins you can modify original core methods. However, there is no way to get an overview of which methods are extended by which plugins. This hackathon project would build a Magerun2 CLI command to search for all plugins and their interceptor methods, and so on.

Hint to self: `Interception/PluginList/PluginList.php`

**Comment by cmuench** [comment]
👍

**Comment by jissereitsma** [comment]
+1 (shameless self promotion)

**Comment by peterjaap** [comment]
It would be cool to have something visual like this too;
![interceptor-sortorder](https://cloud.githubusercontent.com/assets/431360/14777705/1a14ff10-0acf-11e6-9cae-55c67d3ab87b.png)

**Comment by jissereitsma** [comment]
@peterjaap Yes, and connect it to a VR helmet so that you can look at it 360 degrees.

I'm closing my own hackathon early, because it seems a duplicate:
https://github.com/magento-hackathon/magento2-plugin-visualization

**Comment by jissereitsma** [comment]
Further more, yes, definitely a duplicate. The previous hackathon project does exactly what I was after. So I keep this closed.
