### ISSUE TITLE
packer.io

### ISSUE THREAD

**Issue by daim2k5** [magento-hackathon/developer-paradise-2016#7]
Packer is a tool for creating machine and container images for multiple platforms from a single source configuration.

One configuration for all of you ec2,virtualbox.....

**Comment by joshuaswarren** [comment]
I won't be at Dev Paradise :( But I did want to mention that I presented at the Magento Imagine barcamp about my Magento 1+2 Vagrant development environment - https://github.com/joshuaswarren/magescotch - and it's built using Packer, and the Packer scripts are available at https://github.com/joshuaswarren/magemalt - feel free to use, fork, laugh at, PR, or ignore those scripts if you do anything with Packer at the Developer Paradise Hackathon!

**Comment by daim2k5** [comment]
@joshuaswarren thanks,i didn't know that someone did the first steps ;-)
